// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIHjTL1kd82I3U6LfI_PykHdIp169PjtQ',
    appId: '1:846959730603:android:9782737584f3b852507cee',
    messagingSenderId: '846959730603',
    projectId: 'tactical-ops-c41aa',
    storageBucket: 'tactical-ops-c41aa.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNyWgaZh8OXzxwzTYQ8FYbEQ2gp5Dc0fU',
    appId: '1:846959730603:web:265ea2c4f7252d3d507cee',
    messagingSenderId: '846959730603',
    projectId: 'tactical-ops-c41aa',
    authDomain: 'tactical-ops-c41aa.firebaseapp.com',
    storageBucket: 'tactical-ops-c41aa.firebasestorage.app',
    measurementId: 'G-KHFGXLF0YV',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNyWgaZh8OXzxwzTYQ8FYbEQ2gp5Dc0fU',
    appId: '1:846959730603:web:265ea2c4f7252d3d507cee',
    messagingSenderId: '846959730603',
    projectId: 'tactical-ops-c41aa',
    authDomain: 'tactical-ops-c41aa.firebaseapp.com',
    storageBucket: 'tactical-ops-c41aa.firebasestorage.app',
    measurementId: 'G-KHFGXLF0YV',
  );
}
