class BuiltInQuote {
  const BuiltInQuote(this.text, this.author);
  final String text;
  final String author;
}

const builtInQuotes = <BuiltInQuote>[
  BuiltInQuote('The supreme art of war is to subdue the enemy without fighting.', 'Sun Tzu'),
  BuiltInQuote('In the midst of chaos, there is also opportunity.', 'Sun Tzu'),
  BuiltInQuote('Know thy self, know thy enemy. A thousand battles, a thousand victories.', 'Sun Tzu'),
  BuiltInQuote('Victorious warriors win first and then go to war, while defeated warriors go to war first and then seek to win.', 'Sun Tzu'),
  BuiltInQuote('The more you sweat in peace, the less you bleed in war.', 'Norman Schwarzkopf'),
  BuiltInQuote('Leadership is a potent combination of strategy and character. But if you must be without one, be without the strategy.', 'Norman Schwarzkopf'),
  BuiltInQuote('You are not defined by what is done to you. You are defined by what you do with what is done to you.', 'Norman Schwarzkopf'),
  BuiltInQuote('Accept the challenges so that you can feel the exhilaration of victory.', 'George S. Patton'),
  BuiltInQuote('It is foolish and wrong to mourn the men who died. Rather we should thank God that such men lived.', 'George S. Patton'),
  BuiltInQuote('A good plan, violently executed now, is better than a perfect plan next week.', 'George S. Patton'),
  BuiltInQuote('Never tell people how to do things. Tell them what to do and they will surprise you with their ingenuity.', 'George S. Patton'),
  BuiltInQuote('If everyone is thinking alike, then somebody isn\'t thinking.', 'George S. Patton'),
  BuiltInQuote('You don\'t have to be great to start, but you have to start to be great.', 'Zig Ziglar'),
  BuiltInQuote('Discipline equals freedom.', 'Jocko Willink'),
  BuiltInQuote('Don\'t expect to be motivated every day to get out there and make things happen. You won\'t be. Don\'t count on motivation. Count on discipline.', 'Jocko Willink'),
  BuiltInQuote('If you want to be tougher mentally, it is simple: be tougher. Don\'t meditate on it.', 'Jocko Willink'),
  BuiltInQuote('Default: Aggressive.', 'Jocko Willink'),
  BuiltInQuote('Stay hard.', 'David Goggins'),
  BuiltInQuote('You are in danger of living a life so comfortable and soft that you will die without ever realizing your true potential.', 'David Goggins'),
  BuiltInQuote('The most important conversations you\'ll ever have are the ones you\'ll have with yourself.', 'David Goggins'),
  BuiltInQuote('We all have the ability to come from nothing to something.', 'David Goggins'),
  BuiltInQuote('It never gets easier. You just get better.', 'David Goggins'),
  BuiltInQuote('Waste no more time arguing about what a good man should be. Be one.', 'Marcus Aurelius'),
  BuiltInQuote('You have power over your mind — not outside events. Realize this, and you will find strength.', 'Marcus Aurelius'),
  BuiltInQuote('The impediment to action advances action. What stands in the way becomes the way.', 'Marcus Aurelius'),
  BuiltInQuote('Very little is needed to make a happy life; it is all within yourself, in your way of thinking.', 'Marcus Aurelius'),
  BuiltInQuote('Confine yourself to the present.', 'Marcus Aurelius'),
  BuiltInQuote('Do not indulge in dreams of what you do not have, but reckon up the chief of the blessings you do have.', 'Marcus Aurelius'),
  BuiltInQuote('We suffer more in imagination than in reality.', 'Seneca'),
  BuiltInQuote('It is not that I\'m so smart. But I stay with the questions much longer.', 'Seneca'),
  BuiltInQuote('No man was ever wise by chance.', 'Seneca'),
  BuiltInQuote('Begin at once to live, and count each separate day as a separate life.', 'Seneca'),
  BuiltInQuote('Luck is what happens when preparation meets opportunity.', 'Seneca'),
  BuiltInQuote('Make the best use of what is in your power, and take the rest as it happens.', 'Epictetus'),
  BuiltInQuote('It\'s not what happens to you, but how you react to it that matters.', 'Epictetus'),
  BuiltInQuote('He who laughs at himself never runs out of things to laugh at.', 'Epictetus'),
  BuiltInQuote('Seek not the good in external things; seek it in yourself.', 'Epictetus'),
  BuiltInQuote('First say to yourself what you would be; and then do what you have to do.', 'Epictetus'),
  BuiltInQuote('Success is not final, failure is not fatal: it is the courage to continue that counts.', 'Winston Churchill'),
  BuiltInQuote('If you\'re going through hell, keep going.', 'Winston Churchill'),
  BuiltInQuote('The price of greatness is responsibility.', 'Winston Churchill'),
  BuiltInQuote('Continuous effort — not strength or intelligence — is the key to unlocking our potential.', 'Winston Churchill'),
  BuiltInQuote('We make a living by what we get, but we make a life by what we give.', 'Winston Churchill'),
  BuiltInQuote('There are no secrets to success. It is the result of preparation, hard work, and learning from failure.', 'Colin Powell'),
  BuiltInQuote('A dream doesn\'t become reality through magic; it takes sweat, determination, and hard work.', 'Colin Powell'),
  BuiltInQuote('Leadership is solving problems.', 'Colin Powell'),
  BuiltInQuote('The day soldiers stop bringing you their problems is the day you have stopped leading them.', 'Colin Powell'),
  BuiltInQuote('Perpetual optimism is a force multiplier.', 'Colin Powell'),
  BuiltInQuote('Don\'t let what you can\'t do interfere with what you can do.', 'John Wooden'),
  BuiltInQuote('Be more concerned with your character than your reputation.', 'John Wooden'),
  BuiltInQuote('It\'s what you learn after you know it all that counts.', 'John Wooden'),
  BuiltInQuote('Hard work beats talent when talent doesn\'t work hard.', 'Tim Notke'),
  BuiltInQuote('The only easy day was yesterday.', 'US Navy SEALs'),
  BuiltInQuote('Get comfortable being uncomfortable.', 'US Navy SEALs'),
  BuiltInQuote('Under pressure, you don\'t rise to the occasion — you sink to the level of your training.', 'US Navy SEALs'),
  BuiltInQuote('Iron sharpens iron.', 'Proverbs 27:17'),
  BuiltInQuote('Slow is smooth. Smooth is fast.', 'US Special Forces'),
  BuiltInQuote('Two is one, one is none.', 'US Special Forces'),
  BuiltInQuote('Adapt, improvise, overcome.', 'US Marine Corps'),
  BuiltInQuote('Pain is temporary. Quitting lasts forever.', 'Lance Armstrong'),
  BuiltInQuote('The man who has no imagination has no wings.', 'Muhammad Ali'),
  BuiltInQuote('I hated every minute of training, but I said: suffer now and live the rest of your life as a champion.', 'Muhammad Ali'),
];
